### ISSUE TITLE
_ea_ and _eo_ CONJ+[DET,ADP] wrong contractions

### ISSUE THREAD

**Issue by ceramisch** [UniversalDependencies/UD_Portuguese-GSD#5] opened 2018-03-24 20:05 UTC
Strangely, the conjunction _e_ (_and_) appears contracted with the next token _o_ or _a_

This would be correct in Arabic but it is *never* done in Portuguese, _e_ does not contract with any other word.

Correcting the problem for _o_ can be automatic, but _a_ requires manual intervention because it is ambiguous between a determiner (_a_, feminine definite article _the_ -- most cases) and the preposition _a_ (_to_ - rarer).

**Comment by ceramisch** [comment] 2018-03-24 20:06
Complement: 887 cases in the whole corpus

**Comment by dan-zeman** [comment] 2018-03-29 07:49
This seems to be related to / duplicate of https://github.com/UniversalDependencies/UD_Portuguese-BR/pull/1 and https://github.com/UniversalDependencies/docs/issues/294 by @pedrobalage. (But that pull request has not been merged, so yes, we still need a fix.)

**Comment by pedrobalage** [comment] 2018-03-29 07:53
Sorry guys, I didn't have time to follow up this issue. Maybe @ceramisch can help.

**Comment by ceramisch** [comment] 2018-03-30 09:53
I think that the fix cannot be done fully automatically (but I can try to take care of it after release 2.2):
  * we need to manually re-annotate the UPOS of  _o_ and _a_ as PRON or DET
  * then, we need to assign its dependencies: 
      * we can automatically choose _det_ of the next noun to the right, if UPOS=DET, 
      * we can (probably) automatically choose _obj_ if UPOS=PRON, but the target HEAD should be set manually

Then comes my question: any recommendation of an annotation tool capable of dealing with UD2.0 directly, to make this task easier?

**Comment by martinpopel** [comment] 2018-03-30 15:05
> any recommendation of an annotation tool capable of dealing with UD2.0 directly, to make this task easier?

For manual annotation, see http://universaldependencies.org/tools.html#third-party-tools (but not all the tools listed there support full UD 2.0 including enhanced deps).
For automatic edits, there is e.g. [Udapi](http://udapi.github.io/) (I am the main author), which was used e.g. for [detection of Portuguese multi-word tokens](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/pt/addmwt.py) in the [PT-PUD treebank](https://github.com/UniversalDependencies/UD_Portuguese-PUD/tree/master).

**Comment by amir-zeldes** [comment] 2018-03-31 08:27
For automatic edits using simple declarative rules (no coding needed) I can also recommend DepEdit, which we use to convert UD_English-GUM:

https://corpling.uis.georgetown.edu/depedit/

**Comment by arademaker** [comment] 2018-03-31 12:50
@ceramisch we are using our library cl-conllu and the Emacs mode we developed, both listed in the UD tools.

I just checked that this corpus has many validation issues. Are you planning to solve these issues for this release 2.2 ? I can’t promise to help in the next 2 days.

**Comment by dan-zeman** [comment] 2018-03-31 16:30
I think it will be better to leave this corpus out of the shared task. The participants will have enough on their plate even without it, and its inconsistency with Bosque worries me. However, it can still be in the full release 2.2 after the shared task. Then the deadline is June 15.

**Comment by arademaker** [comment] 2020-05-01 19:53
The issue was done by @ceramisch , I only fixed the commits to avoid unnecessary copies of files in the repository. 

The python code from @ceramisch mark all tokens that need manual revision with `XXXXX` and log those tokens in a log file. I moved all logs for a single file `scripts/issue-5-py.log`. My Lisp code `scripts/issue-5.lisp` remove the `XXXXX` from the MISC fields counting them on each file.  Unfortunately, the numbers differ.

**Comment by ceramisch** [comment] 2020-05-05 15:55
The numbers probably differ because I had manually removed the XXXXX from the cases I had already checked manually. I will try to finish the manual verification for the next release so that this issue can be definitely closed. Thanks for sorting things out with the duplications, @arademaker and sorry for the mess: I think now I understand better the idea of branches for UD treebank development :-)

**Comment by arademaker** [comment] 2020-05-05 15:57
I will create a `workbench` branch in the next days and I will split the files into files with only 10 sentences. This will help to edit the files. So please contact me before any change in the files. Anyway, we are now in the freezing period of UD 2.6 release, no changes in dev and master are allowed.

**Comment by ceramisch** [comment] 2020-05-05 16:01
OK, no worries.

**Comment by arademaker** [comment] 2020-05-28 05:10
@ceramisch branch workbench created and folder `documents/` created.

**Comment by arademaker** [comment] 2021-04-20 00:09
see also #9

**Comment by arademaker** [comment] 2021-04-20 00:15
this issue was solved, I didn't find cases of `ea` or `eo`

**Closed by arademaker** 2021-04-20 00:15 UTC
Labels: bug
